cabal-version:      3.0
name:               Tetris
version:            0.1.0.0
synopsis:           Tetris clone for Uni Project
license:            BSD-3-Clause
license-file:       LICENSE
author:             bzuanetti998
maintainer:         bzuanetti54@gmail.com
category:           Game
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings

    exposed-modules:
        Types
        Game
        Board
        Piece
        Collision
        Input
        Update
        Render

    build-depends:
        base ^>=4.20.2.0,
        random

    hs-source-dirs:   src

    default-language: Haskell2010

executable Tetris
    import:           warnings

    main-is:          Main.hs

    build-depends:
        base ^>=4.20.2.0,
        Tetris

    hs-source-dirs:   app

    default-language: Haskell2010

executable tests
    import:           warnings

    main-is:          Tests.hs

    build-depends:
        base ^>=4.20.2.0,
        Tetris

    hs-source-dirs:   test

    default-language: Haskell2010