name:                 Tetris
version:              0.1.0.0
visibility:           public
id:                   Tetris-0.1.0.0-inplace
key:                  Tetris-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           bzuanetti54@gmail.com
author:               bzuanetti998
synopsis:             Tetris clone for Uni Project
category:             Game
abi:                  inplace
exposed:              True
exposed-modules:
    Board Collision Game Input Piece RandomPiece Render Types Update

import-dirs:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/build

library-dirs:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/build

library-dirs-static:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/build

dynamic-library-dirs:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/build

data-dir:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/.

hs-libraries:         HSTetris-0.1.0.0-inplace
depends:              base-4.20.2.0-127e
haddock-interfaces:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/doc/html/Tetris/Tetris.haddock

haddock-html:
    /home/bubble/Desktop/universidade/Haskell/Tetris_Clone_Haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.3/Tetris-0.1.0.0/doc/html/Tetris
